<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use DateTime;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = array(
            array(1, 'AF', 'Afghanistan'),
            array(2, 'AL', 'Albania'),
            array(3, 'DZ', 'Algeria'),
            array(4, 'AS', 'American Samoa'),
            array(5, 'AD', 'Andorra'),
            array(6, 'AO', 'Angola'),
            array(7, 'AI', 'Anguilla'),
            array(8, 'AQ', 'Antarctica'),
            array(9, 'AG', 'Antigua And Barbuda'),
            array(10, 'AR', 'Argentina'),
            array(11, 'AM', 'Armenia'),
            array(12, 'AW', 'Aruba'),
            array(13, 'AU', 'Australia'),
            array(14, 'AT', 'Austria'),
            array(15, 'AZ', 'Azerbaijan'),
            array(16, 'BS', 'Bahamas The'),
            array(17, 'BH', 'Bahrain'),
            array(18, 'BD', 'Bangladesh'),
            array(19, 'BB', 'Barbados'),
            array(20, 'BY', 'Belarus'),
            array(21, 'BE', 'Belgium'),
            array(22, 'BZ', 'Belize'),
            array(23, 'BJ', 'Benin'),
            array(24, 'BM', 'Bermuda'),
            array(25, 'BT', 'Bhutan'),
            array(26, 'BO', 'Bolivia'),
            array(27, 'BA', 'Bosnia and Herzegovina'),
            array(28, 'BW', 'Botswana'),
            array(29, 'BV', 'Bouvet Island'),
            array(30, 'BR', 'Brazil'),
            array(31, 'IO', 'British Indian Ocean Territory'),
            array(32, 'BN', 'Brunei'),
            array(33, 'BG', 'Bulgaria'),
            array(34, 'BF', 'Burkina Faso'),
            array(35, 'BI', 'Burundi'),
            array(36, 'KH', 'Cambodia'),
            array(37, 'CM', 'Cameroon'),
            array(38, 'CA', 'Canada'),
            array(39, 'CV', 'Cape Verde'),
            array(40, 'KY', 'Cayman Islands'),
            array(41, 'CF', 'Central African Republic'),
            array(42, 'TD', 'Chad'),
            array(43, 'CL', 'Chile'),
            array(44, 'CN', 'China'),
            array(45, 'CX', 'Christmas Island'),
            array(46, 'CC', 'Cocos (Keeling) Islands'),
            array(47, 'CO', 'Colombia'),
            array(48, 'KM', 'Comoros'),
            array(49, 'CG', 'Republic Of The Congo'),
            array(50, 'CD', 'Democratic Republic Of The Congo'),
            array(51, 'CK', 'Cook Islands'),
            array(52, 'CR', 'Costa Rica'),
            array(53, 'CI', 'Cote D Ivoire (Ivory Coast)'),
            array(54, 'HR', 'Croatia (Hrvatska)'),
            array(55, 'CU', 'Cuba'),
            array(56, 'CY', 'Cyprus'),
            array(57, 'CZ', 'Czech Republic'),
            array(58, 'DK', 'Denmark'),
            array(59, 'DJ', 'Djibouti'),
            array(60, 'DM', 'Dominica'),
            array(61, 'DO', 'Dominican Republic'),
            array(62, 'TP', 'East Timor'),
            array(63, 'EC', 'Ecuador'),
            array(64, 'EG', 'Egypt'),
            array(65, 'SV', 'El Salvador'),
            array(66, 'GQ', 'Equatorial Guinea'),
            array(67, 'ER', 'Eritrea'),
            array(68, 'EE', 'Estonia'),
            array(69, 'ET', 'Ethiopia'),
            array(70, 'XA', 'External Territories of Australia'),
            array(71, 'FK', 'Falkland Islands'),
            array(72, 'FO', 'Faroe Islands'),
            array(73, 'FJ', 'Fiji Islands'),
            array(74, 'FI', 'Finland'),
            array(75, 'FR', 'France'),
            array(76, 'GF', 'French Guiana'),
            array(77, 'PF', 'French Polynesia'),
            array(78, 'TF', 'French Southern Territories'),
            array(79, 'GA', 'Gabon'),
            array(80, 'GM', 'Gambia The'),
            array(81, 'GE', 'Georgia'),
            array(82, 'DE', 'Germany'),
            array(83, 'GH', 'Ghana'),
            array(84, 'GI', 'Gibraltar'),
            array(85, 'GR', 'Greece'),
            array(86, 'GL', 'Greenland'),
            array(87, 'GD', 'Grenada'),
            array(88, 'GP', 'Guadeloupe'),
            array(89, 'GU', 'Guam'),
            array(90, 'GT', 'Guatemala'),
            array(91, 'XU', 'Guernsey and Alderney'),
            array(92, 'GN', 'Guinea'),
            array(93, 'GW', 'Guinea-Bissau'),
            array(94, 'GY', 'Guyana'),
            array(95, 'HT', 'Haiti'),
            array(96, 'HM', 'Heard and McDonald Islands'),
            array(97, 'HN', 'Honduras'),
            array(98, 'HK', 'Hong Kong S.A.R.'),
            array(99, 'HU', 'Hungary'),
            array(100, 'IS', 'Iceland'),
            array(101, 'IN', 'India'),
            array(102, 'ID', 'Indonesia'),
            array(103, 'IR', 'Iran'),
            array(104, 'IQ', 'Iraq'),
            array(105, 'IE', 'Ireland'),
            array(106, 'IL', 'Israel'),
            array(107, 'IT', 'Italy'),
            array(108, 'JM', 'Jamaica'),
            array(109, 'JP', 'Japan'),
            array(110, 'XJ', 'Jersey'),
            array(111, 'JO', 'Jordan'),
            array(112, 'KZ', 'Kazakhstan'),
            array(113, 'KE', 'Kenya'),
            array(114, 'KI', 'Kiribati'),
            array(115, 'KP', 'Korea North'),
            array(116, 'KR', 'Korea South'),
            array(117, 'KW', 'Kuwait'),
            array(118, 'KG', 'Kyrgyzstan'),
            array(119, 'LA', 'Laos'),
            array(120, 'LV', 'Latvia'),
            array(121, 'LB', 'Lebanon'),
            array(122, 'LS', 'Lesotho'),
            array(123, 'LR', 'Liberia'),
            array(124, 'LY', 'Libya'),
            array(125, 'LI', 'Liechtenstein'),
            array(126, 'LT', 'Lithuania'),
            array(127, 'LU', 'Luxembourg'),
            array(128, 'MO', 'Macau S.A.R.'),
            array(129, 'MK', 'Macedonia'),
            array(130, 'MG', 'Madagascar'),
            array(131, 'MW', 'Malawi'),
            array(132, 'MY', 'Malaysia'),
            array(133, 'MV', 'Maldives'),
            array(134, 'ML', 'Mali'),
            array(135, 'MT', 'Malta'),
            array(136, 'XM', 'Man (Isle of)'),
            array(137, 'MH', 'Marshall Islands'),
            array(138, 'MQ', 'Martinique'),
            array(139, 'MR', 'Mauritania'),
            array(140, 'MU', 'Mauritius'),
            array(141, 'YT', 'Mayotte'),
            array(142, 'MX', 'Mexico'),
            array(143, 'FM', 'Micronesia'),
            array(144, 'MD', 'Moldova'),
            array(145, 'MC', 'Monaco'),
            array(146, 'MN', 'Mongolia'),
            array(147, 'MS', 'Montserrat'),
            array(148, 'MA', 'Morocco'),
            array(149, 'MZ', 'Mozambique'),
            array(150, 'MM', 'Myanmar'),
            array(151, 'NA', 'Namibia'),
            array(152, 'NR', 'Nauru'),
            array(153, 'NP', 'Nepal'),
            array(154, 'AN', 'Netherlands Antilles'),
            array(155, 'NL', 'Netherlands The'),
            array(156, 'NC', 'New Caledonia'),
            array(157, 'NZ', 'New Zealand'),
            array(158, 'NI', 'Nicaragua'),
            array(159, 'NE', 'Niger'),
            array(160, 'NG', 'Nigeria'),
            array(161, 'NU', 'Niue'),
            array(162, 'NF', 'Norfolk Island'),
            array(163, 'MP', 'Northern Mariana Islands'),
            array(164, 'NO', 'Norway'),
            array(165, 'OM', 'Oman'),
            array(166, 'PK', 'Pakistan'),
            array(167, 'PW', 'Palau'),
            array(168, 'PS', 'Palestinian Territory Occupied'),
            array(169, 'PA', 'Panama'),
            array(170, 'PG', 'Papua new Guinea'),
            array(171, 'PY', 'Paraguay'),
            array(172, 'PE', 'Peru'),
            array(173, 'PH', 'Philippines'),
            array(174, 'PN', 'Pitcairn Island'),
            array(175, 'PL', 'Poland'),
            array(176, 'PT', 'Portugal'),
            array(177, 'PR', 'Puerto Rico'),
            array(178, 'QA', 'Qatar'),
            array(179, 'RE', 'Reunion'),
            array(180, 'RO', 'Romania'),
            array(181, 'RU', 'Russia'),
            array(182, 'RW', 'Rwanda'),
            array(183, 'SH', 'Saint Helena'),
            array(184, 'KN', 'Saint Kitts And Nevis'),
            array(185, 'LC', 'Saint Lucia'),
            array(186, 'PM', 'Saint Pierre and Miquelon'),
            array(187, 'VC', 'Saint Vincent And The Grenadines'),
            array(188, 'WS', 'Samoa'),
            array(189, 'SM', 'San Marino'),
            array(190, 'ST', 'Sao Tome and Principe'),
            array(191, 'SA', 'Saudi Arabia'),
            array(192, 'SN', 'Senegal'),
            array(193, 'RS', 'Serbia'),
            array(194, 'SC', 'Seychelles'),
            array(195, 'SL', 'Sierra Leone'),
            array(196, 'SG', 'Singapore'),
            array(197, 'SK', 'Slovakia'),
            array(198, 'SI', 'Slovenia'),
            array(199, 'XG', 'Smaller Territories of the UK'),
            array(200, 'SB', 'Solomon Islands'),
            array(201, 'SO', 'Somalia'),
            array(202, 'ZA', 'South Africa'),
            array(203, 'GS', 'South Georgia'),
            array(204, 'SS', 'South Sudan'),
            array(205, 'ES', 'Spain'),
            array(206, 'LK', 'Sri Lanka'),
            array(207, 'SD', 'Sudan'),
            array(208, 'SR', 'Suriname'),
            array(209, 'SJ', 'Svalbard And Jan Mayen Islands'),
            array(210, 'SZ', 'Swaziland'),
            array(211, 'SE', 'Sweden'),
            array(212, 'CH', 'Switzerland'),
            array(213, 'SY', 'Syria'),
            array(214, 'TW', 'Taiwan'),
            array(215, 'TJ', 'Tajikistan'),
            array(216, 'TZ', 'Tanzania'),
            array(217, 'TH', 'Thailand'),
            array(218, 'TG', 'Togo'),
            array(219, 'TK', 'Tokelau'),
            array(220, 'TO', 'Tonga'),
            array(221, 'TT', 'Trinidad And Tobago'),
            array(222, 'TN', 'Tunisia'),
            array(223, 'TR', 'Turkey'),
            array(224, 'TM', 'Turkmenistan'),
            array(225, 'TC', 'Turks And Caicos Islands'),
            array(226, 'TV', 'Tuvalu'),
            array(227, 'UG', 'Uganda'),
            array(228, 'UA', 'Ukraine'),
            array(229, 'AE', 'United Arab Emirates'),
            array(230, 'GB', 'United Kingdom'),
            array(231, 'US', 'United States'),
            array(232, 'UM', 'United States Minor Outlying Islands'),
            array(233, 'UY', 'Uruguay'),
            array(234, 'UZ', 'Uzbekistan'),
            array(235, 'VU', 'Vanuatu'),
            array(236, 'VA', 'Vatican City State (Holy See)'),
            array(237, 'VE', 'Venezuela'),
            array(238, 'VN', 'Vietnam'),
            array(239, 'VG', 'Virgin Islands (British)'),
            array(240, 'VI', 'Virgin Islands (US)'),
            array(241, 'WF', 'Wallis And Futuna Islands'),
            array(242, 'EH', 'Western Sahara'),
            array(243, 'YE', 'Yemen'),
            array(244, 'YU', 'Yugoslavia'),
            array(245, 'ZM', 'Zambia'),
            array(246, 'ZW', 'Zimbabwe')
        );
          // Cargar los registros
        foreach ($items as $values => $key){
            $r = $values == 0 ? $values+1 :($values+1);
            DB::table('country')
                ->where('sort_name','=',$key[1])
                ->where('name','=',$key[2])
                ->insert([
                    'id' => $key[0],
                    'sort_name' => $key[1],
                    'name' => $key[2],
                    'created_at'=> new DateTime(),
                ]);
        }
    }
}